### ISSUE TITLE
Implement better toml resolution

### ISSUE THREAD

**Issue by roninjin10** [ethereum-optimism/mocktimism#38]
## Description

Currently the config/config.go package loads the toml. The cli/cli.go package can take an optional flag to a toml config. The default behavior is to look at `./mocktimism.toml`. What would be better is if we recursively looked for a mocktimism.toml. E.g. look in current dir, then parent dir, then grandparent dir...

## Tasks

- [x] Implement this feature
- [ ] Write tests
- [ ] Document this behavior in the current config docs

**Comment by Sabnock01** [comment]
Will take this.
